version: '3.8'

services:
  ai-test-generator:
    build: ./ai-test-generator
    container_name: ai-test-generator
    ports:
      - "3000:3000"
    env_file:
      - ./ai-test-generator/.env
    depends_on:
      mongodb:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - my_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - my_network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama serve &
        sleep 10
        ollama pull mistral || echo "Mistral model already downloaded"
        wait

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - my_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # command:
    #   mongod --noauth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:password@localhost:27017/ai_vision --quiet
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  mongodb-data:
  ollama-data:

networks:
  my_network:
    driver: bridge
